name: 'Build and Push GCP docker images'
description: 'Authenticate with gcloud, build image, push image to GCR'
author: 'Michał Masłowski'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  image:
    description: 'Name of the docker image formatted as follow: [your-hostname]/[your-project]/[image]'
    required: true
  project:
    description: 'GCP project'
    required: true
  region:
    description: 'GCP region'
    required: true
  service key:
    description: 'GCP service key with storage and run permissions in base 64'
    required: true
  directory:
    description: 'Directory with Dockerfile. Use . as default'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'